### ISSUE TITLE
Extremly low TPS with animania added on existing modpack (With Sleep ON)

### ISSUE THREAD

**Issue by Tschipp** [capnkirok/animaniamod#168]
marciox25 commented 8 days ago
Expected Behavior
No TPS

Actual Behavior
Low TPS

Steps to Reproduce
Having a good amount of animals,
Wait till the night -> they go to sleep,
The tps on the server goes down till the 4~5tps.
Fixed with disabling sleep on animals. But then another problem appeared. Chichens dont lay eggs if this option is set to false.

Version of Minecraft, version of Animania, Single Player or Server
1.12.2, animania 1.5.1.1

Screenshots encouraged

**capnkirok commented 7 days ago**
Chickens don't lay eggs at night, could be the issue. I will double check the logic regardless and post again.

The sleep lag issue is known (only occurs for some), and a fix is in progress. Cross reference: capnkirok/animaniamod#104

**Comment by Crowfooted** [comment]
I have had a similar issue, except the TPS doesn't just drop - the server has a watchdog crash saying a single tick took 60 seconds. Seemed to be an issue with chickens, and seemed to be related to a check for other entities around them, but I don't know if it applied to other animals.

A related issue with this is that disabling sleep doesn't actually disable sleep itself, but disables the sleep cycle, so animals that were sleeping when the config was disabled will stay sleeping forever until they are woken up by damage etc.

**Comment by mser7** [comment]
yes

**Comment by instinxx** [comment]
I have a similar issue as @Crowfooted. Server randomly crashes due to watchdog timeout.

forge-1.12.2-14.23.4.2760
Animania-1.12.2-1.5.1.1

Crashlog - https://pastebin.com/5WL1Q82n
Possibly related to https://github.com/capnkirok/animaniamod/issues/104
And it seems that chicken sleeping is the issue.

 `java.lang.Error: ServerHangWatchdog detected that a single server tick took 94.80 seconds (should be max 0.05)
	at java.util.Collections$SetFromMap.contains(Collections.java:5459)
	at net.minecraft.util.ClassInheritanceMultiMap.func_181157_b(ClassInheritanceMultiMap.java:54)
	at pl.asie.foamfix.coremod.common.FoamyClassInheritanceMultiMap.access$000(FoamyClassInheritanceMultiMap.java:43)
	at pl.asie.foamfix.coremod.common.FoamyClassInheritanceMultiMap$1.iterator(FoamyClassInheritanceMultiMap.java:51)
	at net.minecraft.world.chunk.Chunk.func_177430_a(Chunk.java:932)
	at net.minecraft.world.World.func_175647_a(World.java:3077)
	at net.minecraft.world.World.func_72872_a(World.java:3060)
	at com.animania.common.helper.AnimaniaHelper.getEntitiesInRange(AnimaniaHelper.java:165)
	at com.animania.common.entities.chickens.ai.EntityAISleep.func_75249_e(EntityAISleep.java:288)
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:102)
	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:763)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2352)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:577)
	at net.minecraft.entity.EntityAgeable.func_70636_d(EntityAgeable.java:178)
	at net.minecraft.entity.passive.EntityAnimal.func_70636_d(SourceFile:43)
	at net.minecraft.entity.passive.EntityChicken.func_70636_d(SourceFile:83)
	at com.animania.common.entities.chickens.EntityAnimaniaChicken.func_70636_d(EntityAnimaniaChicken.java:239)
	at com.animania.common.entities.chickens.EntityHenBase.func_70636_d(EntityHenBase.java:207)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2172)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)
	at net.minecraft.world.World.func_72866_a(World.java:1990)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1952)
	at net.minecraft.world.World.func_72939_s(World.java:1756)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)`

**Comment by capnkirok** [comment]
We have a fix coming in the next update, which will address this. Until then, you can turn sleep off if you are being affected.

**Comment by OreCruncher** [comment]
~~I am having a similar problem, but it is client side FPS (not TPS) that gets drastically reduced.  This only occurs if the sleeping animals are within the view frustrum.  I don't think it is generically a sleeping problem, but rather the fact that these cows fell asleep on top of a trough next to a fence.  When I forced the time to day, and broke the fence to remove the collision the client FPSwent back up.  If you don't think your aforementioned fix will address this I can write a new issue for better tracking.~~

EDIT:  Figured it out.  It is not Animania.  The culprit is Mob Info - an addon that displays graphic information above the critters head when it is hungry/thirsty.  It's MIT so I think I will fix it.  Egad.

**Comment by capnkirok** [comment]
All on this thread, please try the latest version (1.6) with Sleep on, and see if the improvements help.

**Comment by instinxx** [comment]
Using 
Animania-1.12.2-1.6.0.2

Possibly same issue. Crashlog is here https://pastebin.com/7rvd3nyw
Snippit - -- Head --
Thread: Server Watchdog
Stacktrace:
	at net.minecraft.world.gen.ChunkProviderServer.func_186028_c(ChunkProviderServer.java:89)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:135)
	at net.minecraft.world.World.func_72964_e(World.java:310)
	at net.minecraft.world.World.func_175726_f(World.java:305)
	at net.minecraft.world.World.func_180495_p(World.java:911)
	at com.animania.common.entities.generic.ai.GenericAISleep.shouldMoveTo(GenericAISleep.java:114)
	at com.animania.common.entities.generic.ai.GenericAISearchBlock.searchForDestination(GenericAISearchBlock.java:153)
	at com.animania.common.entities.generic.ai.GenericAISearchBlock.func_75250_a(GenericAISearchBlock.java:60)
	at com.animania.common.entities.generic.ai.GenericAISleep.func_75250_a(GenericAISleep.java:77)
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:94)
	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:763)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2352)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:577)
	at net.minecraft.entity.EntityAgeable.func_70636_d(EntityAgeable.java:178)
	at net.minecraft.entity.passive.EntityAnimal.func_70636_d(SourceFile:43)
	at com.animania.common.entities.pigs.EntityAnimaniaPig.func_70636_d(EntityAnimaniaPig.java:715)
	at com.animania.common.entities.pigs.EntitySowBase.func_70636_d(EntitySowBase.java:584)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2172)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)
	at net.minecraft.world.World.func_72866_a(World.java:1993)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1955)
	at net.minecraft.world.World.func_72939_s(World.java:1759)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)

**Comment by goalcam** [comment]
I haven't experienced crashing on my server, but since moving to 1.6.x, I've noticed my tickrate crashing through the floor during night if sleep is turned on. Daytime performance is good.

I reverted back to the last version of 1.5.x and the problem disappeared.

**Comment by capnkirok** [comment]
Another report... https://paste.ee/p/dfAtn

**Comment by MidoriMushrooms** [comment]
Hi. Getting the same issue on my server as well. TPS tanks to below 7 and we traced the problem back to animania. https://pastebin.com/GcNqhSDm

Running Animania 1.0.6.2, Forge 2768

**Comment by Tschipp** [comment]
Ok, I think I've *finally* nailed this issue. I tested it with the current build and the tps dropped town to 10. With my updated code it remains at 20 all the time.
