### ISSUE TITLE
Server Crash when Client Enters Server

### ISSUE THREAD

**Issue by AngelusQQ** [capnkirok/animaniamod#184]
Expected Behavior: 
- Made a new world server and Login

Actual Behavior:
- Made a new world server, login and server immediately crashes

Minecraft 1.12.2 Server
forge-1.12.2-14.23.5.2768
Animania 1.12.2 version 1.6

> ---- Minecraft Crash Report ----
> // I blame RazzleberryFox, Purplicious_Cow, cy4n, Tschipp, ZeAmateis, Timmypote, Raptorfarian, vroulas, and TheJurassicAlien, author of Animania.
> 
> Time: 2018-10-29 02:00:32 EDT
> Description: Exception in server tick loop
> 
> java.lang.NoClassDefFoundError: net/minecraft/client/util/ITooltipFlag
>     at java.lang.Class.getDeclaredMethods0(Native Method)
>     at java.lang.Class.privateGetDeclaredMethods(Unknown Source)
>     at java.lang.Class.getDeclaredMethod(Unknown Source)
>     at net.minecraftforge.fml.relauncher.ReflectionHelper.findMethod(ReflectionHelper.java:225)
>     at com.animania.common.handler.ItemHandler.regItemEggColors(ItemHandler.java:309)
>     at com.animania.common.events.EntityEventHandler.onEntityJoinWorld(EntityEventHandler.java:79)
>     at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_425_EntityEventHandler_onEntityJoinWorld_EntityJoinWorldEvent.invoke(.dynamic)
>     at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
>     at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:687)
>     at org.spongepowered.common.SpongeImplHooks.firePlayerJoinSpawnEvent(SpongeImplHooks.java:1248)
>     at org.spongepowered.common.event.tracking.PhaseTracker.spawnEntity(PhaseTracker.java:870)
>     at net.minecraft.world.WorldServer.spawnEntity(WorldServer.java:2734)
>     at net.minecraft.server.management.PlayerList.handler$playerLoggedIn2$zjl000(PlayerList.java:2053)
>     at net.minecraft.server.management.PlayerList.playerLoggedIn(PlayerList.java:368)
>     at net.minecraft.server.management.PlayerList.initializeConnectionToPlayer(PlayerList.java:1591)
>     at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.completeServerSideConnection(NetworkDispatcher.java:255)
>     at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.access$100(NetworkDispatcher.java:72)
>     at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.update(NetworkDispatcher.java:205)
>     at net.minecraft.network.NetworkManager.processReceivedPackets(NetworkManager.java:285)
>     at net.minecraft.network.NetworkSystem.networkTick(NetworkSystem.java:180)
>     at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:790)
>     at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:397)
>     at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
>     at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
>     at java.lang.Thread.run(Unknown Source)
> Caused by: java.lang.ClassNotFoundException: net.minecraft.client.util.ITooltipFlag
>     at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
>     at java.lang.ClassLoader.loadClass(Unknown Source)
>     at java.lang.ClassLoader.loadClass(Unknown Source)
>     ... 25 more
> 
> 
> A detailed walkthrough of the error, its code path and all known details is as follows:
>

**Comment by Tschipp** [comment]
Hmmm... didn’t notice that in my testing... will investigate... @capnkirok if this is true we will need a hotfix

**Comment by davidPoult** [comment]
Can also confirm this is happening to me,

Minecraft 1.12.2 Server
forge-1.12.2-14.23.5.2772
Animania 1.12.2 version 1.6

```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  Born in a Barn (Born+In+A+Barn+V1.8-1.12-1.0.jar)
  LoadingPlugin (Quark-r1.5-130.jar)
  SplashAnimationCoremod (SplashAnimation-0.2.0.jar)
  Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.2-1.12.2.jar)
  DynamicSurroundingsCore (DynamicSurroundings-1.12.2-3.4.9.16.jar)
  llibrary (llibrary-core-1.0.8-1.12.2.jar)
  CTMCorePlugin (CTM-MC1.12.2-0.3.2.20.jar)
Contact their authors BEFORE contacting forge

// Oops.

Time: 2018/10/29 11:11 AM
Description: Exception in server tick loop

java.lang.NoClassDefFoundError: net/minecraft/client/util/ITooltipFlag
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.getDeclaredMethod(Class.java:2128)
	at net.minecraftforge.fml.relauncher.ReflectionHelper.findMethod(ReflectionHelper.java:225)
	at com.animania.common.handler.ItemHandler.regItemEggColors(ItemHandler.java:309)
	at com.animania.common.events.EntityEventHandler.onEntityJoinWorld(EntityEventHandler.java:79)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_312_EntityEventHandler_onEntityJoinWorld_EntityJoinWorldEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraft.world.World.func_72838_d(World.java:1206)
	at net.minecraft.world.WorldServer.func_72838_d(WorldServer.java:1058)
	at net.minecraft.server.management.PlayerList.func_72377_c(PlayerList.java:377)
	at net.minecraft.server.management.PlayerList.initializeConnectionToPlayer(PlayerList.java:166)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.completeServerSideConnection(NetworkDispatcher.java:255)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.access$100(NetworkDispatcher.java:72)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:205)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:790)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.util.ITooltipFlag
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 23 more
Caused by: java.lang.NullPointerException
```

**Comment by digi-tal-it** [comment]
Yep, same problem here:

https://pastebin.com/Bw3g4jqr

**Comment by capnkirok** [comment]
Looks like a conflict with Thermal Expansion. We'll need to do a hotfix.

**Comment by KenyMylankca** [comment]
i'm having the same crash. that in regItemEggColors

**Comment by TheRealDadbeard** [comment]
> i'm having the same crash. that in regItemEggColors

Jupp the same!

https://hastebin.com/pepicajujo.rb
