### ISSUE TITLE
[Bug] Achievements are broken when updating to the new version

### ISSUE THREAD

**Issue by CalaMariGold** [capnkirok/animaniamod#454]
### Expected Behavior
Using Triumph, we have a bunch of custom achievements and we disable many mod achievements.

### Actual Behavior
Animania breaks Triumph and none of our custom achievements load.

### Steps to Reproduce
Install animania, farm, extras + triumph and make custom achievements. Or just clone https://github.com/Rebirth-of-the-Night/Rebirth-Of-The-Night and test it yourself

### Version of Minecraft, version of Animania, Single Player or Server
1.12.2, base-2.0.0.23, single

**Comment by Tschipp** [comment]
Oh dear, that's bad... I had to do some bad stuff to get the addon advancements working, seems like I broke everything else in the process...

**Comment by CalaMariGold** [comment]
@Tschipp Is it possible there may be a temporary fix? Maybe a config to disable all animania achievements? We'd love to be able to update to the latest Animania version but this issue is holding us back

**Comment by Tschipp** [comment]
I need to do further testing, I hope I can find some time soon

**Comment by CalaMariGold** [comment]
Bump, still an issue on the latest Animania release.

Thanks <3

**Comment by sleeperstakes** [comment]
Bump, still finding this to be an issue

**Comment by Igfig** [comment]
I'm also having this issue. I second the request to make Animania advancements optional; I didn't even realize there were any.

**Comment by Unit72101** [comment]
And when server tries load advancement when someone have some achievement so it's just crash. 

Description: Exception in server tick loop

java.lang.NullPointerException
     at net.minecraft.advancements.AdvancementProgress.handler$zzp000$onIsDone(SourceFile:1170)
     at net.minecraft.advancements.AdvancementProgress.isDone(SourceFile)
     at net.minecraft.advancements.AdvancementProgress$Serializer.serialize(SourceFile:231)
     at net.minecraft.advancements.AdvancementProgress$Serializer.serialize(SourceFile:217)
     at com.google.gson.internal.bind.TreeTypeAdapter.write(TreeTypeAdapter.java:81)
     at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69)
     at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.write(MapTypeAdapterFactory.java:208)
     at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.write(MapTypeAdapterFactory.java:145)
     at com.google.gson.Gson.toJson(Gson.java:669)
     at com.google.gson.Gson.toJson(Gson.java:648)
     at com.google.gson.Gson.toJson(Gson.java:603)
     at com.google.gson.Gson.toJson(Gson.java:583)
     at net.minecraft.advancements.PlayerAdvancements.save(PlayerAdvancements.java:189)
     at net.minecraft.server.management.PlayerList.writePlayerData(PlayerList.java:360)
     at net.minecraft.server.management.PlayerList.saveAllPlayerData(PlayerList.java:943)
     at net.minecraft.server.MinecraftServer.constant$zjg000$getSaveTickInterval(MinecraftServer.java:4566)
     at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:687)
     at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
     at java.lang.Thread.run(Thread.java:748)
