### ISSUE TITLE
java.lang.NoClassDefFoundError: com/animania/common/entities/sheep/EntityEweBase

### ISSUE THREAD

**Issue by Powermonkey00** [capnkirok/animaniamod#455]
java.lang.NoClassDefFoundError: com/animania/common/entities/sheep/EntityEweBase
	at org.orecruncher.dsurround.client.renderer.AnimaniaBadge.scale(AnimaniaBadge.java:109)
	at org.orecruncher.dsurround.client.renderer.BadgeRenderLayer.func_177141_a(BadgeRenderLayer.java:127)
	at net.minecraft.client.renderer.entity.RenderLivingBase.func_177093_a(RenderLivingBase.java:561)
	at net.minecraft.client.renderer.entity.RenderLivingBase.func_76986_a(RenderLivingBase.java:270)
	at net.minecraft.client.renderer.entity.RenderLiving.func_76986_a(RenderLiving.java:50)
	at net.minecraft.client.renderer.entity.RenderLiving.func_76986_a(RenderLiving.java:16)
	at net.minecraft.client.renderer.entity.RenderManager.func_188391_a(RenderManager.java:412)
	at net.minecraft.client.renderer.entity.RenderManager.func_188388_a(RenderManager.java:392)
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:849)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1801)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1614)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1385)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: com.animania.common.entities.sheep.EntityEweBase
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 21 more
Caused by: java.lang.NullPointerException

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at org.orecruncher.dsurround.client.renderer.AnimaniaBadge.scale(AnimaniaBadge.java:109)
	at org.orecruncher.dsurround.client.renderer.BadgeRenderLayer.func_177141_a(BadgeRenderLayer.java:127)
	at net.minecraft.client.renderer.entity.RenderLivingBase.func_177093_a(RenderLivingBase.java:561)
	at net.minecraft.client.renderer.entity.RenderLivingBase.func_76986_a(RenderLivingBase.java:270)
	at net.minecraft.client.renderer.entity.RenderLiving.func_76986_a(RenderLiving.java:50)
	at net.minecraft.client.renderer.entity.RenderLiving.func_76986_a(RenderLiving.java:16)

-- Entity being rendered --
Details:
	Entity Type: animania:sow_hampshire (com.animania.addons.farm.common.entity.pigs.PigHampshire.EntitySowHampshire)
	Entity ID: 801
	Entity Name: Hampshire Sow
	Entity's Exact location: 10.45, 71.00, 237.45
	Entity's Block location: World: (10,71,237), Chunk: (at 10,4,13 in 0,14; contains blocks 0,0,224 to 15,255,239), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null

-- Renderer details --
Details:
	Assigned renderer: com.animania.addons.farm.client.render.pigs.RenderSowHampshire@2df3c7d8
	Location: -8.88,1.00,22.41 - World: (-9,1,22), Chunk: (at 7,0,6 in -1,1; contains blocks -16,0,16 to -1,255,31), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Rotation: -42.1875
	Delta: 0.14003527
Stacktrace:
	at net.minecraft.client.renderer.entity.RenderManager.func_188391_a(RenderManager.java:412)
	at net.minecraft.client.renderer.entity.RenderManager.func_188388_a(RenderManager.java:392)
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:849)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1801)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1614)

-- Affected level --
Details:
	Level name: MpServer
	All players: 2 total; [EntityPlayerSP['Powermonkey00'/11017491, l='MpServer', x=19.21, y=70.00, z=215.16], EntityOtherPlayerMP['Laganthrope'/10694146, l='MpServer', x=-31.59, y=64.00, z=237.46]]
	Chunk stats: MultiplayerChunkCache: 289, 289
	Level seed: 0
	Level generator: ID 06 - BIOMESOP, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-52,64,267), Chunk: (at 12,4,11 in -4,16; contains blocks -64,0,256 to -49,255,271), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 1638468 game time, 1428333 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 83 total; [EntityBabySpider['Baby Spider'/11343017, l='MpServer', x=-18.16, y=12.00, z=192.67], EntityZombieChicken['Zombie Chicken'/11347113, l='MpServer', x=11.51, y=52.00, z=173.51], EntityFlameSpewer['Flame Spewer'/11327145, l='MpServer', x=24.50, y=10.58, z=253.50], EntityBabySpider['Baby Spider'/11343016, l='MpServer', x=-18.79, y=13.00, z=193.05], EntityArchaeologist['Archaeologist'/773, l='MpServer', x=42.00, y=12.00, z=223.00], EntityBabyZombie['Baby Zombie'/11347112, l='MpServer', x=11.50, y=52.45, z=173.41], EntityBabySpider['Baby Spider'/11347114, l='MpServer', x=-35.50, y=23.00, z=215.50], EntityBabySpider['Baby Spider'/11343013, l='MpServer', x=-19.21, y=14.80, z=195.49], EntityBabySpider['Baby Spider'/11343015, l='MpServer', x=-19.47, y=13.00, z=193.64], EntityZombieChicken['Zombie Chicken'/11347111, l='MpServer', x=-1.68, y=53.00, z=174.37], EntityBabySpider['Baby Spider'/11343014, l='MpServer', x=-13.64, y=13.75, z=195.55], EntityBabyZombie['Baby Zombie'/11347110, l='MpServer', x=-1.58, y=53.45, z=174.35], EntityButterfly['Butterfly'/11329185, l='MpServer', x=53.75, y=69.20, z=186.01], EntityMotherSpider['Mother Spider'/11343011, l='MpServer', x=-19.30, y=14.10, z=195.53], EntityMaid['Cirno'/6865255, l='MpServer', x=-34.16, y=65.00, z=249.43], EntityNautilus['Nautilus'/4733532, l='MpServer', x=76.50, y=23.00, z=260.50], EntityNautilus['Nautilus'/4733533, l='MpServer', x=73.50, y=23.00, z=260.50], EntityNautilus['Nautilus'/4733535, l='MpServer', x=73.50, y=23.00, z=264.50], EntitySkeletonWarrior['Skeleton Warrior'/11343024, l='MpServer', x=-3.50, y=25.00, z=183.50], EntityArchaeologist['Archaeologist'/797, l='MpServer', x=59.00, y=12.00, z=155.00], EntityCreeper['Creeper'/11322290, l='MpServer', x=73.50, y=33.00, z=217.50], EntityBat['Bat'/11318706, l='MpServer', x=78.25, y=28.10, z=193.68], EntityBat['Bat'/11354546, l='MpServer', x=32.04, y=18.10, z=135.09], EntitySowHampshire['Hampshire Sow'/799, l='MpServer', x=-10.23, y=68.00, z=269.99], EntityGaiaSatyress['Satyress'/11342989, l='MpServer', x=9.74, y=63.00, z=198.44], EntitySowHampshire['Hampshire Sow'/801, l='MpServer', x=10.45, y=71.00, z=237.45], EntityGaiaSatyress['Satyress'/11342988, l='MpServer', x=6.50, y=63.00, z=199.50], EntityGlassItemFrame['Glass Item Frame'/10212287, l='MpServer', x=-31.50, y=66.50, z=237.97], EntityZombie['Zombie'/11347077, l='MpServer', x=58.50, y=46.00, z=196.50], EntityNautilus['Nautilus'/4733536, l='MpServer', x=70.50, y=23.00, z=263.50], EntityBat['Bat'/11329180, l='MpServer', x=-55.05, y=31.93, z=251.68], EntityStoneling['Stoneling'/11346334, l='MpServer', x=46.95, y=25.00, z=282.67], EntityStallionDraftHorse['Draft Horse Stallion'/4332927, l='MpServer', x=72.45, y=62.60, z=209.10], EntitySkeleton['Skeleton'/11346413, l='MpServer', x=18.50, y=16.00, z=215.50], EntityPlayerSP['Powermonkey00'/11017491, l='MpServer', x=19.21, y=70.00, z=215.16], EntityOtherPlayerMP['Laganthrope'/10694146, l='MpServer', x=-31.59, y=64.00, z=237.46], EntityStallionDraftHorse['Draft Horse Stallion'/4062061, l='MpServer', x=31.26, y=69.00, z=198.94], EntityEnchantedBook['Bewitched Tome'/11347452, l='MpServer', x=-37.50, y=22.00, z=275.50], EntityGaiaPropVase['Ancient Vase'/11344127, l='MpServer', x=45.50, y=24.00, z=236.50], EntityBabyCreeper['Baby Creeper'/11322366, l='MpServer', x=-15.16, y=32.00, z=277.47], EntityGaiaArachne['Arachne'/11344126, l='MpServer', x=-5.50, y=27.00, z=214.50], EntityBuckAlpine['Alpine Buck'/5180950, l='MpServer', x=42.82, y=65.00, z=217.16], EntityZotzpyre['Zotzpyre'/11316215, l='MpServer', x=-8.50, y=45.00, z=276.50], EntityBuckAlpine['Alpine Buck'/4062047, l='MpServer', x=57.99, y=76.00, z=173.04], EntityBat['Bat'/11355343, l='MpServer', x=78.65, y=28.81, z=198.69], EntityBabySkeleton['Baby Skeleton'/11343049, l='MpServer', x=35.06, y=20.00, z=240.50], EntityBabySkeleton['Baby Skeleton'/11343048, l='MpServer', x=43.50, y=30.00, z=197.50], EntitySkeletonWarrior['Skeleton Warrior'/11357640, l='MpServer', x=-54.50, y=20.00, z=141.50], EntityFlameSpewer['Flame Spewer'/11331786, l='MpServer', x=-43.50, y=10.58, z=250.50], EntityGaiaCreep['Creep'/11322314, l='MpServer', x=14.68, y=53.00, z=219.50], EntityDoeFainting['Fainting Doe'/616, l='MpServer', x=-13.82, y=64.00, z=184.77], EntitySkeleton['Skeleton'/11346398, l='MpServer', x=-10.50, y=27.00, z=194.50], EntitySkeletonWarrior['Skeleton Warrior'/11357648, l='MpServer', x=25.27, y=27.00, z=134.50], EntityGoblin['Goblin'/11358253, l='MpServer', x=-50.19, y=25.00, z=172.50], EntityLamprey['Lamprey'/2800041, l='MpServer', x=81.89, y=62.00, z=250.65], EntityBabySpider['Baby Spider'/11352873, l='MpServer', x=-12.97, y=23.00, z=153.02], EntitySkeletonWarrior['Skeleton Warrior'/11352865, l='MpServer', x=13.50, y=51.00, z=140.50], EntityFestiveCreeper['Festive Creeper'/11358753, l='MpServer', x=-24.50, y=35.00, z=198.50], EntityEweMerino['Merino Ewe'/11028006, l='MpServer', x=-5.07, y=73.00, z=150.95], EntityMinecartChest['Minecart with Chest'/670, l='MpServer', x=-34.50, y=21.06, z=182.50], EntityOtherPlayerMP['Laganthrope'/10694146, l='MpServer', x=-31.59, y=64.00, z=237.46], EntityZotzpyre['Zotzpyre'/11316239, l='MpServer', x=5.50, y=40.00, z=168.50], EntityZombieChicken['Zombie Chicken'/11346441, l='MpServer', x=-12.23, y=16.00, z=264.50], EntityBabyZombie['Baby Zombie'/11346440, l='MpServer', x=-12.21, y=16.45, z=264.40], EntityHorse['Horse'/678, l='MpServer', x=-29.01, y=66.00, z=175.13], EntityZombieChicken['Zombie Chicken'/11346443, l='MpServer', x=-8.40, y=15.00, z=261.65], EntityBabyZombie['Baby Zombie'/11346442, l='MpServer', x=-8.49, y=15.45, z=261.63], EntityHorse['Horse'/681, l='MpServer', x=-46.68, y=73.00, z=161.79], EntityFlameSpewer['Flame Spewer'/11332102, l='MpServer', x=75.50, y=10.58, z=234.50], EntityDoeFainting['Fainting Doe'/683, l='MpServer', x=56.09, y=75.00, z=171.76], EntityEnchantedBook['Bewitched Tome'/11352861, l='MpServer', x=54.50, y=30.00, z=276.50], EntityCreeper['Creeper'/11342873, l='MpServer', x=-6.50, y=38.00, z=243.50], EntitySkeletonWarrior['Skeleton Warrior'/11200791, l='MpServer', x=-48.50, y=57.00, z=243.29], EntityCreeper['Creeper'/11347053, l='MpServer', x=-49.50, y=14.00, z=236.50], EntityBat['Bat'/11354734, l='MpServer', x=52.59, y=36.08, z=275.75], EntitySkeletonWarrior['Skeleton Warrior'/11324520, l='MpServer', x=33.50, y=16.00, z=238.50], EntitySkeletonWarrior['Skeleton Warrior'/11327849, l='MpServer', x=-26.50, y=40.00, z=151.50], EntitySkeleton['Skeleton'/11342974, l='MpServer', x=33.50, y=20.00, z=241.50], EntityWroughtnaut['Ferrous Wroughtnaut'/742, l='MpServer', x=10.50, y=50.00, z=160.50], EntityBat['Bat'/11343175, l='MpServer', x=10.27, y=39.04, z=136.61], EntityArchaeologist['Archaeologist'/748, l='MpServer', x=-20.00, y=16.00, z=277.00], EntitySkeletonWarrior['Skeleton Warrior'/11028039, l='MpServer', x=81.50, y=40.00, z=220.50], EntitySkeletonWarrior['Skeleton Warrior'/11316304, l='MpServer', x=35.50, y=25.00, z=254.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:532)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:419)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by Tschipp** [comment]
Disable the dynamic surrounding animania integration.

**Comment by srwaggon** [comment]
@Tschipp How does a person do that?

**Comment by Tschipp** [comment]
Now you need to update dynamic surroundings to the latest version. There is a fix for this out.

**Comment by srwaggon** [comment]
This worked for me.

For posterity, I was able to download the latest beta of Dynamic Surroundings here:
https://www.curseforge.com/minecraft/mc-mods/dynamic-surroundings/files

By the time this is being seen, the latest Dynamic Surroundings may have created a proper release containing the fix.

Also note that the 1.12.2 Dynamic Surroundings Beta currently requires a mixin which is not provided by default (check the main description). As I use the CurseForge launcher, it was added for me automatically.

**Comment by Laki09** [comment]
I don't know how to do any of this stuff, I downloaded the latest 1.12.2 version and put it into the mody folder of the modpack, but then there was an error
[crash-2021-04-03_12.38.25-client.txt](https://github.com/capnkirok/animaniamod/files/6252370/crash-2021-04-03_12.38.25-client.txt)
