### ISSUE TITLE
[Crash] animania:model_cart/wagon Not Registered

### ISSUE THREAD

**Issue by Mastermind27** [capnkirok/animaniamod#487]
**Expected Behaviour**
No Crash

**Actual Behaviour**
Crash On Start up

**Steps to Reproduce**

**Version of Minecraft, version of Animania, Single Player or Server**
Minecraft Forge 1.12.2 forge-14.23.5.2854
animania-1.12.2-base-2.0.1.26
animania-1.12.2-farm-1.0.1
Single player

**Crash log, latest.log**
---- Minecraft Crash Report ----

WARNING: coremods are present:
  XaeroMinimapPlugin (Xaeros_Minimap_21.0.0_Forge_1.12.jar)
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  TransformLoader (DynamicSurroundings-1.12.2-3.6.1.0.jar)
  BetterFoliageLoader (BetterFoliage-MC1.12-2.3.1.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  ForgelinPlugin (Forgelin-1.8.4.jar)
  Quark Plugin (Quark-r1.6-179.jar)
  XaeroWorldMapPlugin (XaerosWorldMap_1.11.7_Forge_1.12.jar)
  ThiccEntities Plugin (thiccentities-1.4.jar)
Contact their authors BEFORE contacting forge

// I bet Cylons wouldn't have this problem.

Time: 1/17/21 1:36 AM
Description: Initializing game

com.leviathanstudio.craftstudio.client.exception.CSResourceNotRegisteredException: You are trying to acces "animania:model_cart", but it's not registered
	at com.leviathanstudio.craftstudio.client.model.ModelCraftStudio.<init>(ModelCraftStudio.java:72)
	at com.leviathanstudio.craftstudio.client.model.ModelCraftStudio.<init>(ModelCraftStudio.java:62)
	at com.animania.addons.farm.client.render.props.RenderCart.<init>(RenderCart.java:16)
	at com.animania.addons.farm.client.render.props.RenderCart$Factory.createRenderFor(RenderCart.java:77)
	at net.minecraftforge.fml.client.registry.RenderingRegistry.register(RenderingRegistry.java:77)
	at net.minecraftforge.fml.client.registry.RenderingRegistry.loadEntityRenderers(RenderingRegistry.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.optifine.reflect.Reflector.call(Reflector.java:799)
	at net.minecraft.client.renderer.entity.RenderManager.<init>(RenderManager.java:248)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:518)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.leviathanstudio.craftstudio.client.model.ModelCraftStudio.<init>(ModelCraftStudio.java:72)
	at com.leviathanstudio.craftstudio.client.model.ModelCraftStudio.<init>(ModelCraftStudio.java:62)
	at com.animania.addons.farm.client.render.props.RenderCart.<init>(RenderCart.java:16)
	at com.animania.addons.farm.client.render.props.RenderCart$Factory.createRenderFor(RenderCart.java:77)
	at net.minecraftforge.fml.client.registry.RenderingRegistry.register(RenderingRegistry.java:77)
	at net.minecraftforge.fml.client.registry.RenderingRegistry.loadEntityRenderers(RenderingRegistry.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.optifine.reflect.Reflector.call(Reflector.java:799)
	at net.minecraft.client.renderer.entity.RenderManager.<init>(RenderManager.java:248)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:518)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1131955088 bytes (1079 MB) / 2816999424 bytes (2686 MB) up to 8589934592 bytes (8192 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx9216m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2854 Optifine OptiFine_1.12.2_HD_U_F5 44 mods loaded, 44 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                  | Version                  | Source                                             | Signature                                |
	|:----- |:------------------- |:------------------------ |:-------------------------------------------------- |:---------------------------------------- |
	| LCH   | minecraft           | 1.12.2                   | minecraft.jar                                      | None                                     |
	| LCH   | mcp                 | 9.42                     | minecraft.jar                                      | None                                     |
	| LCH   | FML                 | 8.0.99.99                | forge-1.12.2-14.23.5.2854.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | forge               | 14.23.5.2854             | forge-1.12.2-14.23.5.2854.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | xaerominimap_core   | 1.12.2-1.0               | minecraft.jar                                      | None                                     |
	| LCH   | xaeroworldmap_core  | 1.12.2-1.0               | minecraft.jar                                      | None                                     |
	| LCH   | damageindicatorsmod | 1.0                      | [1.12.2]DamageIndicatorsMod-3.5.1.jar              | None                                     |
	| LCH   | biomesoplenty       | 7.0.1.2441               | BiomesOPlenty-1.12.2-7.0.1.2441-universal.jar      | None                                     |
	| LCH   | craftstudioapi      | 1.0.0                    | CraftStudioAPI-universal-1.0.1.95-mc1.12-alpha.jar | None                                     |
	| LCH   | animania            | 2.0.0.23                 | animania-1.12.2-base-2.0.0.23.jar                  | None                                     |
	| LCH   | jei                 | 4.16.1.301               | jei_1.12.2-4.16.1.301.jar                          | None                                     |
	| LCH   | quark               | r1.6-179                 | Quark-r1.6-179.jar                                 | None                                     |
	| LCH   | autoreglib          | 1.3-32                   | AutoRegLib-1.3-32.jar                              | None                                     |
	| LCH   | veinminer           | 0.38.2                   | VeinMiner-1.12-0.38.2.647+b31535a.jar              | None                                     |
	| LCH   | mmdlib              | 1.0.0-rc2                | MMDLib-1.12-1.0.0-rc2.36.jar                       | None                                     |
	| LCH   | basemetals          | 2.5.0-rc2                | BaseMetals-1.12-2.5.0-rc2.332.jar                  | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCH   | baseminerals        | 2.5.0-rc2                | BaseMinerals-1.12-2.5.0-rc2.69.jar                 | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCH   | forgelin            | 1.8.4                    | Forgelin-1.8.4.jar                                 | None                                     |
	| LCH   | betterfoliage       | 2.3.1                    | BetterFoliage-MC1.12-2.3.1.jar                     | None                                     |
	| LCH   | bookworm            | 1.12.2-2.5.2.1           | bookworm-1.12.2-2.5.2.1.jar                        | None                                     |
	| LCH   | customspawner       | 3.11.4                   | CustomMobSpawner-3.11.5.jar                        | None                                     |
	| LCH   | orelib              | 3.6.0.1                  | OreLib-1.12.2-3.6.0.1.jar                          | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| LCH   | dsurround           | 3.6.1.0                  | DynamicSurroundings-1.12.2-3.6.1.0.jar             | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| LCH   | dynamictrees        | 1.12.2-0.9.21            | DynamicTrees-1.12.2-0.9.21.jar                     | None                                     |
	| LCH   | dynamictreesbop     | 1.12.2-1.4.4             | DynamicTreesBOP-1.12.2-1.4.4.jar                   | None                                     |
	| LCH   | llibrary            | 1.7.20                   | llibrary-1.7.20-1.12.2.jar                         | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| LCH   | fossil              | 8.0.4                    | fossilsarcheology-8.0.4.jar                        | None                                     |
	| LCH   | inventorytweaks     | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                           | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| LCH   | kleeslabs           | 5.4.12                   | KleeSlabs_1.12.2-5.4.12.jar                        | None                                     |
	| LCH   | neat                | 1.4-17                   | Neat 1.4-17.jar                                    | None                                     |
	| LCH   | orespawn            | 3.3.1                    | OreSpawn-1.12-3.3.1.179.jar                        | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCH   | potioncore          | 1.9_for_1.12.2           | PotionCore-1.9_for_1.12.2.jar                      | None                                     |
	| LCH   | prehistoricspawns   | 1.0                      | prehistoricspawns-1.1.jar                          | None                                     |
	| LCH   | somanyenchantments  | 0.5.0                    | SoManyEnchantments-0.5.0.jar                       | None                                     |
	| LCH   | spartanweaponry     | beta 1.3.8               | SpartanWeaponry-1.12.2-beta-1.3.8.jar              | None                                     |
	| LCH   | spartanbm           | 0.3                      | spartanbm-0.3.jar                                  | None                                     |
	| LCH   | spartancompat       | @VERSION@                | spartancompat-1.2.3.jar                            | None                                     |
	| LCH   | spartanshields      | 1.5.4                    | SpartanShields-1.12.2-1.5.4.jar                    | None                                     |
	| LCH   | thiccentities       | GRADLE:VERSION           | thiccentities-1.4.jar                              | None                                     |
	| LCH   | veinminermodsupport | 0.38.2                   | VeinMiner-1.12-0.38.2.647+b31535a.jar              | None                                     |
	| LCH   | worldedit           | 6.1.10                   | worldedit-forge-mc1.12.2-6.1.10-dist.jar           | None                                     |
	| LCH   | xaerominimap        | 21.0.0                   | Xaeros_Minimap_21.0.0_Forge_1.12.jar               | None                                     |
	| LCH   | xaeroworldmap       | 1.11.7                   | XaerosWorldMap_1.11.7_Forge_1.12.jar               | None                                     |
	| LCH   | zawa                | 1.12.2-2.1.0             | zawa-1.12.2-2.1.0.jar                              | 3ee471ded1bba54aa82f4f5ca5ca82dd67b8ef42 |

	Loaded coremods (and transformers): 
XaeroMinimapPlugin (Xaeros_Minimap_21.0.0_Forge_1.12.jar)
  xaero.common.core.transformer.ChunkTransformer
  xaero.common.core.transformer.NetHandlerPlayClientTransformer
  xaero.common.core.transformer.EntityPlayerTransformer
  xaero.common.core.transformer.AbstractClientPlayerTransformer
  xaero.common.core.transformer.WorldClientTransformer
  xaero.common.core.transformer.EntityPlayerSPTransformer
  xaero.common.core.transformer.PlayerListTransformer
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
TransformLoader (DynamicSurroundings-1.12.2-3.6.1.0.jar)
  
BetterFoliageLoader (BetterFoliage-MC1.12-2.3.1.jar)
  mods.betterfoliage.loader.BetterFoliageTransformer
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
ForgelinPlugin (Forgelin-1.8.4.jar)
  
Quark Plugin (Quark-r1.6-179.jar)
  vazkii.quark.base.asm.ClassTransformer
XaeroWorldMapPlugin (XaerosWorldMap_1.11.7_Forge_1.12.jar)
  xaero.map.core.transformer.ChunkTransformer
  xaero.map.core.transformer.NetHandlerPlayClientTransformer
  xaero.map.core.transformer.EntityPlayerTransformer
  xaero.map.core.transformer.AbstractClientPlayerTransformer
  xaero.map.core.transformer.WorldClientTransformer
  xaero.map.core.transformer.PlayerListTransformer
ThiccEntities Plugin (thiccentities-1.4.jar)
  wiresegal.thicc.asm.ThiccAsmTransformer
	GL info: ' Vendor: 'Intel' Version: '4.6.0 - Build 26.20.100.8142' Renderer: 'Intel(R) HD Graphics 620'
	Launched Version: forge-14.23.5.2854
	LWJGL: 2.9.4
	OpenGL: Intel(R) HD Graphics 620 GL version 4.6.0 - Build 26.20.100.8142, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
	OptiFine Version: OptiFine_1.12.2_HD_U_F5
	OptiFine Build: 20191204-141934
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 - Build 26.20.100.8142
	OpenGlRenderer: Intel(R) HD Graphics 620
	OpenGlVendor: Intel
	CpuCount: 4

**Comment by carboniris** [comment]
Having this issue as well.

**Comment by ghost** [comment]
Same here
