### ISSUE TITLE
[Crash] - Entity being ticked --   Entity Type: animania:rooster_leghorn

### ISSUE THREAD

**Issue by WAvataW** [capnkirok/animaniamod#520]
### Expected Behavior
--

### Actual Behavior
crash the server 

### Steps to Reproduce
I really don't know worked fine for a days now the game is crashing and says is the "animania:rooster" . if i join the server the server will crash because i will load the rooster

### Version of Minecraft, version of Animania, Single Player or Server
animania-1.12.2-extra-1.0.2.28
server

### Crash log, latest.log
---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 2021-04-13 23:50:35 BST
Description: Ticking entity

java.lang.NullPointerException
    at net.minecraft.pathfinding.WalkNodeProcessor.getSafePoint(WalkNodeProcessor.java:193)
    at net.minecraft.pathfinding.WalkNodeProcessor.getSafePoint(WalkNodeProcessor.java:220)
    at net.minecraft.pathfinditProcessor.findPathOptions(WalkNodeProcessor.java:114)
    at net.minecraft.pathfinding.PathFinder.findPath(SourceFile:82)
    at net.minecraft.pathfinding.PathFinder.findPath(SourceFile:40)
    at net.minecraft.pathfinding.PathFinder.findPath(SourceFile:30)
    at net.minecraft.pathfinding.PathNavigate.getPathToPos(SourceFile:114)
    at net.minecraft.pathfinding.PathNavigateGround.getPathToPos(SourceFile:65)
    at net.minecraft.pathfinding.PathNavigate.getPathToXYZ(SourceFile:93)
    at net.minecraft.pathfinding.PathNavigate.tryMoveToXYZ(SourceFile:143)
    at net.minecraft.entity.ai.EntityAIWander.startExecuting(SourceFile:65)
    at net.minecraft.entity.ai.EntityAITasks.onUpdateTasks(SourceFile:102)
    at net.minecraft.entity.EntityLiving.updateEntityActionState(EntityLiving.java:763)
    at net.minecraft.entity.EntityLivingBase.onLivingUpdate(EntityLivingBase.java:2359)
    at net.minecraft.entity.EntityLiving.onLivingUpdate(EntityLiving.java:577)
    at net.minecraft.entity.EntityAgeable.onLivingUpdate(EntityAgeable.java:178)
    at net.minecraft.entity.passive.EntityAnimal.onLivingUpdate(SourceFile:43)
    at net.minecraft.entity.passive.EntityChicken.onLivingUpdate(SourceFile:83)
    at com.animania.addons.farm.common.entity.chickens.EntityAnimaniaChicken.onLivingUpdate(EntityAnimaniaChicken.java:208)
    at com.animania.addons.farm.common.entity.chickens.EntityRoosterBase.onLivingUpdate(EntityRoosterBase.java:170)
    at net.minecraft.entity.EntityLivingBase.onUpdate(EntityLivingBase.java:2179)
    at net.minecraft.entity.EntityLiving.onUpdate(EntityLiving.java:295)
    at net.minecraft.world.World.updateEntityWithOptionalForce(World.java:1996)
    at net.minecraft.world.WorldServer.updateEntityWithOptionalForce(WorldServer.java:832)
    at net.minecraft.world.World.updateEntity(World.java:1958)
    at net.minecraft.world.World.redirect$zbi000$updateEntity(World.java:5123)
    at net.minecraft.world.World.updateEntities(World.java:1762)
    at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:613)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:767)
    at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:397)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Entity being ticked --
  Entity Type: animania:rooster_leghorn (com.animania.addons.farm.common.entity.chickens.ChickenLeghorn.EntityRoosterLeghorn)
  Entity ID: 303307
  Entity Name: Leghorn Rooster
  Entity's Exact location: -895.35, 71.94, -2311.59
  Entity's Block location: World: (-896,71,-2312), Chunk: (at 0,4,8 in -56,-145; contains blocks -896,0,-2320 to -881,255,-2305), Region: (-2,-5; contains chunks -64,-160 to -33,-129, blocks -1024,0,-2560 to -513,255,-2049)
  Entity's Momentum: 0.00, -0.08, 0.00
  Entity's Passengers: []
  Entity's Vehicle: ~~ERROR~~ NullPointerException: null
  Entity NBT: {IsChickenJockey:0b,Watered:1b,HurtByTimestamp:248,ForgeData:{thebetweenlands.has_no_equipment:1b},SleepTimer:-100.0f,Attributes:[{Base:0.0d,Name:"attribute.name.aether.slash"},{Base:0.0d,Name:"attribute.name.aether.pierce"},{Base:0.0d,Name:"attribute.name.aether.impact"},{Base:6.0d,Name:"generic.maxHealth"},{Base:0.0d,Name:"generic.knockbackResistance"},{Base:0.29d,Name:"generic.movementSpeed"},{Base:0.0d,Name:"generic.armor"},{Base:0.0d,Name:"generic.armorToughness"},{Base:1.0d,Name:"forge.swimSpeed"},{Base:16.0d,Name:"generic.followRange"},{Base:2.0d,Name:"generic.attackDamage"}],Invulnerable:0b,FallFlying:0b,ForcedAge:0,PortalCooldown:0,AbsorptionAmount:0.0f,FallDistance:0.0f,InLove:0,DeathTime:0s,Handfed:0b,ForgeCaps:{"tinkertoolleveling:entityxp":[],"thebetweenlands:entity_gems":{gems:[]},"thebetweenlands:custom_step_sound":{},"llibrary:extendedentitydatacapability":{"mm:living":{frozenYaw:0.0f,freezeProgress:0.0f,frozenPitch:0.0f,prevHasAI:0b,freezeDecayDelay:0,frozenYawHead:0.0f,frozenLimbSwingAmount:0.0f,frozenRenderYawOffset:0.0f,frozenSwingProgress:0.0f},"Ice And Fire - Chicken Property Tracker":{TimeUntilNextEgg:1682},"Ice And Fire - Siren Property Tracker":{CharmedBySiren:0b,SirenID:0},"Fossils - Mammal Tracker":{EmbryoProgress:0,Embryo:-1},"Ice And Fire - Frozen Property Tracker":{TicksUntilUnfrozen:0,IsFrozen:0b},"Ice and Fire - Player Property Tracker":{DismountedDragon:0b,GauntletDamage:0,DreadPortalZ:0,DreadPortalY:0,DreadPortalX:0},"Ice And Fire - Chain Property Tracker":{ConnectedEntities:[]},"Ice And Fire - Stone Property Tracker":{StoneBreakLvl:0,TurnedToStone:0b}},"aether:entityinfo":{hasSpawnArea:0b},"thebetweenlands:puppet":{ticks:0,guard:0b,recruitmentCost:0,stay:0b},"enderutilities:entity_portal_cooldown":{LastInPortal:0L},"twilightforest:cap_shield":{permshields:0,tempshields:0},"thebetweenlands:equipment":{amuletSlots:1},"aether:statuseffects":{},"lycanitesmobs:iextendedentity":{},"metallurgy:punch_effect":{hasAiDisabled:1b,knockbackTicks:0,ticks:0}},HandDropChances:[0.085f,0.085f],PersistenceRequired:1b,Age:1,Motion:[0.0d,-0.0784000015258789d,0.0d],Leashed:0b,Fed:1b,UUIDLeast:-8200109468476596608L,Health:2.0f,LeftHanded:0b,Air:300s,OnGround:1b,Dimension:0,Rotation:[59.68596f,0.0f],UpdateBlocked:0b,HandItems:[{},{}],ArmorDropChances:[0.085f,0.085f,0.085f,0.085f],EggLayTime:1000,Interacted:0b,Sleep:0b,UUIDMost:-8690334822446510509L,Pos:[-895.353070880575d,71.9375d,-2311.588443748223d],Fire:-1s,ArmorItems:[{},{},{},{}],CrowTime:0,CrowDuration:0,CanPickUpLoot:0b,HurtTime:0s}

-- Affected level --
  Level name: world
  All players: 3 total; [EntityPlayerMP['evoice9'/224, l='world', x=513.67, y=16.00, z=-2662.09], EntityPlayerMP['Dejotinha'/217928, l='world', x=-860.27, y=71.00, z=-2286.32], EntityPlayerMP['WAvataW'/136392, l='world', x=-849.16, y=72.00, z=-2293.38]]
  Chunk stats: ServerChunkCache: 1474 Drop: 0
  Level seed: 195362900801921186
  Level generator: ID 00 - default, ver 1. Features enabled: true
  Level generator options: 
  Level spawn location: World: (-1019,79,-847), Chunk: (at 5,4,1 in -64,-53; contains blocks -1024,0,-848 to -1009,255,-833), Region: (-2,-2; contains chunks -64,-64 to -33,-33, blocks -1024,0,-1024 to -513,255,-513)
  Level time: 2737743 game time, 2743886 day time
  Level dimension: 0
  Level storage version: 0x04ABD - Anvil
  Level weather: Rain time: 49914 (now: false), thunder time: 80289 (now: false)
  Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false

**Comment by WAvataW** [comment]
---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 2021-04-15 02:02:23 BST
Description: Ticking entity

java.lang.NullPointerException
    at net.minecraft.pathfinding.WalkNodeProcessor.getSafePoint(WalkNodeProcessor.java:193)
    at net.minecraft.pathfinding.WalkNodeProcessor.getSafePoint(WalkNodeProcessor.java:220)
    at net.minecraft.pathfinding.WalkNodeProcessor.findPathOptions(WalkNodeProcessor.java:115)
    at net.minecraft.pathfinding.PathFinder.findPath(SourceFile:82)
    at net.minecraft.pathfinding.PathFinder.findPath(SourceFile:40)
    at net.minecraft.pathfinding.PathFinder.findPath(SourceFile:30)
    at net.minecraft.pathfinding.PathNavigate.getPathToPos(SourceFile:114)
    at net.minecraft.pathfinding.PathNavigateGround.getPathToPos(SourceFile:51)
    at net.minecraft.pathfinding.PathNavigate.getPathToXYZ(SourceFile:93)
    at net.minecraft.pathfinding.PathNavigate.tryMoveToXYZ(SourceFile:143)
    at net.minecraft.entity.ai.EntityAIWander.startExecuting(SourceFile:65)
    at net.minecraft.entity.ai.EntityAITasks.onUpdateTasks(SourceFile:102)
    at net.minecraft.entity.EntityLiving.updateEntityActionState(EntityLiving.java:763)
    at net.minecraft.entity.EntityLivingBase.onLivingUpdate(EntityLivingBase.java:2359)
    at net.minecraft.entity.EntityLiving.onLivingUpdate(EntityLiving.java:577)
    at net.minecraft.entity.EntityAgeable.onLivingUpdate(EntityAgeable.java:178)
    at net.minecraft.entity.passive.EntityAnimal.onLivingUpdate(SourceFile:43)
    at net.minecraft.entity.passive.EntityChicken.onLivingUpdate(SourceFile:83)
    at com.animania.addons.farm.common.entity.chickens.EntityAnimaniaChicken.onLivingUpdate(EntityAnimaniaChicken.java:208)
    at com.animania.addons.farm.common.entity.chickens.EntityHenBase.onLivingUpdate(EntityHenBase.java:179)
    at net.minecraft.entity.EntityLivingBase.onUpdate(EntityLivingBase.java:2179)
    at net.minecraft.entity.EntityLiving.onUpdate(EntityLiving.java:295)
    at net.minecraft.world.World.updateEntityWithOptionalForce(World.java:1996)
    at net.minecraft.world.WorldServer.updateEntityWithOptionalForce(WorldServer.java:832)
    at net.minecraft.world.World.updateEntity(World.java:1958)
    at net.minecraft.world.World.redirect$zbi000$updateEntity(World.java:5123)
    at net.minecraft.world.World.updateEntities(World.java:1762)
    at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:613)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:767)
    at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:397)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Unknown Source)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Entity being ticked --
  Entity Type: animania:hen_leghorn (com.animania.addons.farm.common.entity.chickens.ChickenLeghorn.EntityHenLeghorn)
  Entity ID: 523
  Entity Name: Leghorn Hen
  Entity's Exact location: -900.47, 72.00, -2305.28
  Entity's Block location: World: (-901,72,-2306), Chunk: (at 11,4,14 in -57,-145; contains blocks -912,0,-2320 to -897,255,-2305), Region: (-2,-5; contains chunks -64,-160 to -33,-129, blocks -1024,0,-2560 to -513,255,-2049)
  Entity's Momentum: 0.00, -0.08, 0.00
  Entity's Passengers: []
  Entity's Vehicle: ~~ERROR~~ NullPointerException: null
  Entity NBT: {IsChickenJockey:0b,Watered:1b,HurtByTimestamp:20516,ForgeData:{thebetweenlands.has_no_equipment:1b},SleepTimer:-100.0f,Attributes:[{Base:0.0d,Name:"attribute.name.aether.slash"},{Base:0.0d,Name:"attribute.name.aether.pierce"},{Base:0.0d,Name:"attribute.name.aether.impact"},{Base:6.0d,Name:"generic.maxHealth"},{Base:0.0d,Name:"generic.knockbackResistance"},{Base:0.29d,Name:"generic.movementSpeed"},{Base:0.0d,Name:"generic.armor"},{Base:0.0d,Name:"generic.armorToughness"},{Base:1.0d,Name:"forge.swimSpeed"},{Base:16.0d,Name:"generic.followRange"},{Base:1.5d,Modifiers:[{UUIDMost:2478452629826324956L,UUIDLeast:-7247530463494186011L,Amount:-4.0d,Operation:0,Name:"effect.weakness 0"}],Name:"generic.attackDamage"}],Invulnerable:0b,FallFlying:0b,ForcedAge:0,PortalCooldown:0,AbsorptionAmount:0.0f,FallDistance:0.0f,InLove:0,Laid:0b,DeathTime:0s,Handfed:0b,ForgeCaps:{"tinkertoolleveling:entityxp":[],"thebetweenlands:entity_gems":{gems:[]},"thebetweenlands:custom_step_sound":{},"llibrary:extendedentitydatacapability":{"mm:living":{frozenYaw:0.0f,freezeProgress:0.0f,frozenPitch:0.0f,prevHasAI:0b,freezeDecayDelay:0,frozenYawHead:0.0f,frozenLimbSwingAmount:0.0f,frozenRenderYawOffset:0.0f,frozenSwingProgress:0.0f},"Ice And Fire - Chicken Property Tracker":{TimeUntilNextEgg:7031},"Ice And Fire - Siren Property Tracker":{CharmedBySiren:0b,SirenID:0},"Fossils - Mammal Tracker":{EmbryoProgress:0,Embryo:-1},"Ice And Fire - Frozen Property Tracker":{TicksUntilUnfrozen:0,IsFrozen:0b},"Ice and Fire - Player Property Tracker":{DismountedDragon:0b,GauntletDamage:0,DreadPortalZ:0,DreadPortalY:0,DreadPortalX:0},"Ice And Fire - Chain Property Tracker":{ConnectedEntities:[]},"Ice And Fire - Stone Property Tracker":{StoneBreakLvl:0,TurnedToStone:0b}},"aether:entityinfo":{hasSpawnArea:0b},"thebetweenlands:puppet":{ticks:0,guard:0b,recruitmentCost:0,stay:0b},"enderutilities:entity_portal_cooldown":{LastInPortal:0L},"twilightforest:cap_shield":{permshields:0,tempshields:0},"thebetweenlands:equipment":{amuletSlots:1},"aether:statuseffects":{},"lycanitesmobs:iextendedentity":{},"metallurgy:punch_effect":{hasAiDisabled:1b,knockbackTicks:0,ticks:0}},HandDropChances:[0.085f,0.085f],PersistenceRequired:1b,Age:1,Motion:[0.0d,-0.0784000015258789d,0.0d],Leashed:0b,Fed:0b,UUIDLeast:-5660911191732514048L,Health:5.6f,LeftHanded:0b,Air:300s,OnGround:1b,Dimension:0,Rotation:[176.04922f,0.0f],UpdateBlocked:0b,HandItems:[{},{}],ArmorDropChances:[0.085f,0.085f,0.085f,0.085f],EggLayTime:1000,Interacted:1b,Sleep:0b,LaidTimer:-1,UUIDMost:4188291474980159814L,Pos:[-900.4663637688637d,72.0d,-2305.280461689013d],Fire:0s,ArmorItems:[{},{},{},{}],CanPickUpLoot:0b,HurtTime:0s,ActiveEffects:[{Ambient:0b,CurativeItems:[{id:"minecraft:milk_bucket",Count:1b,Damage:0s}],ShowParticles:0b,Duration:1,Id:18,Amplifier:0b}]}

-- Affected level --
  Level name: world
  All players: 1 total; [EntityPlayerMP['WAvataW'/207, l='world', x=-875.95, y=69.00, z=-2287.26]]
  Chunk stats: ServerChunkCache: 469 Drop: 0
  Level seed: 195362900801921186
  Level generator: ID 00 - default, ver 1. Features enabled: true
  Level generator options: 
  Level spawn location: World: (-1019,79,-847), Chunk: (at 5,4,1 in -64,-53; contains blocks -1024,0,-848 to -1009,255,-833), Region: (-2,-2; contains chunks -64,-64 to -33,-33, blocks -1024,0,-1024 to -513,255,-513)
  Level time: 3177295 game time, 3183438 day time
  Level dimension: 0
  Level storage version: 0x04ABD - Anvil
  Level weather: Rain time: 5074 (now: true), thunder time: 133670 (now: false)
  Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false

**Comment by Tschipp** [comment]
strange, never seen that before

**Comment by WAvataW** [comment]
> strange, never seen that before

i m testing if the problem if from the mod "Carry On" i pick up the Leghorn . using that mod. maybe corrupt them after i pick up them. i will remove the mod and and for some days . see if i don't have the same crash. them i will tell you something

**Comment by KaleThyself** [comment]
I've found that this bug is replicable with naturally generated Animania mobs. 
Tested on version: `1.12.2-1.7.3`.
